### ISSUE TITLE
Responde GAMMA:

### ISSUE THREAD

**Issue by renzoorpelli** [renzoorpelli/TP_SO_i3_Equipo_100#11]
d-¿Las ramas creadas por BETA y GAMMA quedan con datos actualizados?
e-¿Detalle (explique) los problemas que tuvieron al hacer el merge?
f-¿que debió hacer (todos los comandos) en el punto 7 para poder hacer lo pedido?

**Comment by rk2040** [comment]
Respuestas d- e- f- Gamma
